- id: uncrustify
  name: uncrustify
  entry: uncrustify-hook
  description: Formats C, C++, Objective-C, Java, D, and Vala code
  # D, vala currently aren't valid file types. See https://github.com/pre-commit/identify/issues/258
  types_or: [c, c++, c#, objective-c, java]
  language: python
